# Generated by Django 5.1.7 on 2025-03-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_biometric'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('cl_balance', models.FloatField(default=12)),
                ('ml_balance', models.FloatField(default=7)),
                ('lop', models.FloatField(default=0)),
                ('comp_off', models.FloatField(default=0)),
                ('paternity_balance', models.FloatField(default=2)),
                ('onduty_exam', models.FloatField(default=7)),
                ('onduty_official', models.FloatField(default=0)),
                ('onduty_research', models.FloatField(default=3)),
                ('summer_vacation', models.FloatField(default=14)),
                ('winter_vacation', models.FloatField(default=0)),
                ('month_leave_taken', models.JSONField(default=dict)),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Medical Leave', 'Medical Leave'), ('Comp Off', 'Comp Off'), ('On Duty Exam', 'On Duty exam'), ('On Duty Official', 'On Duty official'), ('On Duty Research', 'On Duty research'), ('Paternity Leave', 'Paternity Leave'), ('Summer Vacation', 'Summer Vacation'), ('Winter Vacation', 'Winter Vacation')], default='Sick Leave', max_length=50)),
                ('time_period', models.CharField(choices=[('fullDay', 'Full Day'), ('firstHalf', 'First Half'), ('secondHalf', 'Second Half')], default='fullDay', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_department', models.CharField(blank=True, max_length=20, null=True)),
                ('leave_days', models.FloatField()),
                ('extra_days_worked', models.PositiveIntegerField(default=0)),
                ('paternity_days_taken', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee')),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
            },
        ),
    ]
