# Generated by Django 5.1.7 on 2025-03-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='receiver_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
