# Generated by Django 5.1.7 on 2025-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='receiver_id',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
