# Generated by Django 5.1.4 on 2025-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biometric',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
