# Generated by Django 5.2 on 2025-04-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_biometric'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/degree/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/experience/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marksheet',
            field=models.FileField(blank=True, null=True, upload_to='certificates/marksheet/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notice_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
