# Generated by Django 5.2 on 2025-04-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_degree_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
