# Generated by Django 5.2 on 2025-04-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_payslip_role_payslip_basic_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
