# Generated by Django 5.1.7 on 2025-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
