# Generated by Django 5.1.7 on 2025-03-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenses_user_department_expenses_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='Expense_type',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='user_department',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='user_name',
        ),
        migrations.AddField(
            model_name='expenses',
            name='bills_upload',
            field=models.FileField(blank=True, null=True, upload_to='expense_bills/'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='emp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='employee_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Reimbursement', 'Reimbursement')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Own Vehicle', 'Own Vehicle'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
    ]
