# Generated by Django 5.1.7 on 2025-03-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expenses_expense_type_remove_expenses_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='emp_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], max_length=20, null=True),
        ),
    ]
