# Generated by Django 5.1.7 on 2025-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expenses_emp_department_alter_expenses_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='employee_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
