# Generated by Django 5.1.7 on 2025-03-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expenses_employee_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='bills_upload',
            field=models.ImageField(blank=True, null=True, upload_to='expense_bills/'),
        ),
    ]
