# Generated by Django 5.1.7 on 2025-03-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expenses_bills_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
