# Generated by Django 5.1.5 on 2025-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='acknowledge_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='acknowledge_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
