# Generated by Django 5.1.5 on 2025-02-05 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_announcement_acknowledge_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='acknowledge_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='acknowledge_count',
        ),
        migrations.AddField(
            model_name='announcement',
            name='acknowledge_users',
            field=models.ManyToManyField(blank=True, related_name='acknowledged_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='acknowledge_users',
            field=models.ManyToManyField(blank=True, related_name='acknowledged_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
