# Generated by Django 5.1.5 on 2025-02-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_remove_announcement_acknowledge_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
