# Generated by Django 5.1.5 on 2025-02-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_announcement_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='department',
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
