# Generated by Django 5.1.4 on 2025-02-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_admin',
            name='leave_type',
            field=models.CharField(choices=[('Medical Leave', 'Medical Leave'), ('Casual Leave', 'Casual Leave'), ('Comp Off', 'Comp Off'), ('On Duty exam', 'On Duty exam'), ('On Duty official', 'On Duty official'), ('On Duty research', 'On Duty research'), ('Paternity Leave', 'Paternity Leave'), ('Summer Vacation', 'Summer Vacation'), ('Winter Vacation', 'Winter Vacation')], default='Casual Leave', max_length=50),
        ),
    ]
