# Generated by Django 5.1.4 on 2025-02-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_leave_admin_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_admin',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Medical Leave', 'Medical Leave'), ('Comp Off', 'Comp Off'), ('On Duty Exam', 'On Duty exam'), ('On Duty Official', 'On Duty official'), ('On Duty Research', 'On Duty research'), ('Paternity Leave', 'Paternity Leave'), ('Summer Vacation', 'Summer Vacation'), ('Winter Vacation', 'Winter Vacation')], default='Casual Leave', max_length=50),
        ),
    ]
