# Generated by Django 5.1.6 on 2025-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Missing', max_length=10)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('working_hours', models.DurationField(blank=True, null=True)),
                ('late_arrival', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
