# Generated by Django 5.1.6 on 2025-03-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_attendance', '0002_alter_attendance_late_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
