# Generated by Django 5.1.7 on 2025-04-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_attendance', '0005_attendance_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='submit_regularize',
            field=models.BooleanField(default=False),
        ),
    ]
