# Generated by Django 5.1.4 on 2025-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
