# Generated by Django 5.1.4 on 2025-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
