# Generated by Django 5.1.4 on 2025-02-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_message_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
    ]
