# Generated by Django 5.1.7 on 2025-03-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='mail/'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
