# Generated by Django 5.1.6 on 2025-02-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_category_assigned_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.category'),
            preserve_default=False,
        ),
    ]
