# Generated by Django 5.1.6 on 2025-02-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_subcategory_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='subcategory',
        ),
    ]
