# Generated by Django 5.1.6 on 2025-02-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_ticket_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
