# Generated by Django 5.1.4 on 2025-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_subcategory_alter_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
