# Generated by Django 5.1.7 on 2025-03-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
