# Generated by Django 5.1.7 on 2025-03-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticket_escalation_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='escalation_deadline',
            new_name='escalation',
        ),
    ]
